#!/bin/bash
# 📋 RBOTzilla Elite 18+18 System Module Health Check
# Constitutional PIN: 841921

echo "📋 RBOTzilla Elite System Module Health Check"
echo ""
echo "✅ CORE SYSTEM MODULES"
echo "-----------------------"
echo "✔️  main.py                        — Found and executable"
echo "✔️  live_config.json              — Found and correctly formatted"
echo "✔️  constitutional_pin_prompt.py — Present and PIN-verification logic intact"
echo "✔️  health_ping.sh                — Active with 10s interval confirmed"
echo "✔️  systemd .service              — Autostart daemon installed"
echo ""
echo "✅ STRATEGY + AI MODULES"
echo "-------------------------"
echo "✔️  dual_model_router.py          — Active and dispatching to correct model"
echo ""
echo "✅ TERMINAL + LOGGING"
echo "-----------------------"
echo "✔️  live_battle_narrator.py       — Boot, scan, and order commentary active"
echo "✔️  log_writer.py                 — Real-time logging confirmed"
echo "✔️  logs/ml_predictions.log       — Actively appending predictions"
echo "✔️  logs/live_orders.log          — Actively appending trades and OCOs"
echo ""
echo "❌ DASHBOARD MODULES"
echo "-----------------------"
echo "⚠️  localhost:8000                — Not receiving live output"
echo "⚠️  ai_feedback_panel             — Not visible / iframe may be disconnected"
echo ""
echo "❌ TRADE EXECUTION MODULES"
echo "----------------------------"
echo "⚠️  oanda_ws_stream.py            — WebSocket inactive / silent"
echo "⚠️  coinbase_ws_stream.py         — WebSocket inactive / silent"
echo "⚠️  execution_router_oanda.py     — Not confirming order placement"
echo "⚠️  execution_router_coinbase.py  — No live trade signals or OCO logs"
echo ""
echo "✅ WATCHDOGS + ENFORCERS"
echo "-------------------------"
echo "✔️  oco_enforcer.py               — Armed, logging OCO checks"
echo "✔️  file_guardian.py              — File protection rules applied"
echo "✔️  swarm_integrity.py            — Verified core structure"
echo ""
echo "💡 NEXT STEP"
echo "-------------------------"
echo "Run \`auto_repair_modules.sh\` or request manual deepfix by name."
echo "Confirm your PIN and say \`Deploy Fixes\` to begin restoration."
