from typing import Protocol, Optional, Dict, Any

class Broker(Protocol):
    def price(self, symbol: str) -> float: ...
    def place_order_oco(self, symbol: str, side: str, units: int,
                        entry: float, tp: float, sl: float,
                        client_id: str, extras: Optional[Dict[str, Any]] = None) -> Dict[str, Any]: ...
    def cancel(self, broker_order_id: str) -> None: ...
    def open_position(self, symbol: str) -> Dict[str, Any]: ...
    def consolidate(self, symbol: str) -> Dict[str, Any]: ...
